stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./gradlew assembleRelease
    - ./gradlew assembleDebug

deploy:
  stage: deploy
  script:
    - mkdir public
    - cp app/release/app-release.apk public/
    - cp app/debug/app-debug.apk public/
  artifacts:
    paths:
      - public
  only:
    - master
